-- Canonical schema entrypoint for BuyerHQ rebuild.
-- Use the following scripts in order:
--   1) supabase/setup_production_db.sql
--   2) supabase/seed_rebuild.sql
--
-- This file intentionally points to the canonical scripts to avoid
-- maintaining conflicting duplicate schema definitions.
